# Generated by Django 4.1.1 on 2023-05-26 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_remove_contracts_manager_clients_logo'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='ტელეფონი')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.clients')),
            ],
        ),
    ]
