# Generated by Django 4.1.1 on 2023-05-26 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_clientuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientUser',
        ),
    ]
