# Generated by Django 4.1.1 on 2023-05-26 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_clientuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientuser',
            name='phone',
        ),
    ]
