# Generated by Django 4.1.1 on 2023-05-26 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_clientuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('pos_id', models.AutoField(primary_key=True, serialize=False)),
                ('pos_name', models.CharField(max_length=30, verbose_name='თანამდებობა')),
                ('pos_desc', models.CharField(blank=True, max_length=70, null=True, verbose_name='თანამდებობის აღწერა')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='users.positions')),
            ],
        ),
    ]
