# Generated by Django 4.1.1 on 2023-05-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_clientuser_clientuser_id_employeeuser_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='clientuser_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employeeuser',
            name='employee_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
