# Generated by Django 4.1.1 on 2023-05-28 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_remove_requests_sent_from'),
        ('users', '0012_alter_clientuser_clientuser_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientUser',
        ),
    ]
