# Generated by Django 4.1.1 on 2023-05-28 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_countries_country_id'),
        ('users', '0013_delete_clientuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('clientuser_id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.clients')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
