# Generated by Django 4.1.1 on 2023-06-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_clientuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='user_photo/default_user_picture.png', null=True, upload_to='user_photo'),
        ),
    ]
