# Generated by Django 4.1.1 on 2023-08-24 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_remove_requests_sent_from_delete_estimations_and_more'),
        ('users', '0015_alter_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeuser',
            name='position',
        ),
        migrations.RemoveField(
            model_name='employeeuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='ClientUser',
        ),
        migrations.DeleteModel(
            name='EmployeeUser',
        ),
        migrations.DeleteModel(
            name='Positions',
        ),
    ]
