# Generated by Django 4.1.1 on 2023-05-22 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driverdocs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('car_vin', models.CharField(max_length=17, verbose_name='VIN')),
                ('car_reg_number', models.CharField(max_length=8, verbose_name='სახელმწიფო ნომერი')),
                ('driver', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='driverdocs.drivers')),
            ],
            options={
                'verbose_name_plural': 'მანქანები',
            },
        ),
        migrations.CreateModel(
            name='DocCategories',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=45, verbose_name='კატეგორია')),
            ],
            options={
                'verbose_name_plural': 'დოკუმენტების კატეგორიები',
            },
        ),
        migrations.CreateModel(
            name='Trailers',
            fields=[
                ('trailer_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('trailer_vin', models.CharField(max_length=17, verbose_name='VIN')),
                ('trailer_reg_number', models.CharField(max_length=8, verbose_name='სახელმწიფო ნომერი')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cardocs.cars')),
            ],
            options={
                'verbose_name_plural': 'ტრეილერები',
            },
        ),
        migrations.CreateModel(
            name='TrailerDocuments',
            fields=[
                ('trailer_doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('trailer_doc_number', models.CharField(max_length=22, verbose_name='დოკუმენტის ნომერი')),
                ('trailer_doc_given', models.DateField(verbose_name='გაცემის თარიღი')),
                ('trailer_doc_expire', models.DateField(verbose_name='მოქმედების ვადა')),
                ('relevance', models.BooleanField(default=True, verbose_name='აქტუალურობა')),
                ('trailer_doc_path', models.FileField(upload_to='uploads/trailer_docs', verbose_name='ფაილი')),
                ('trailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardocs.trailers', verbose_name='ტრეილერის ID')),
                ('trailer_doc_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cardocs.doccategories', verbose_name='კატეგორია')),
            ],
            options={
                'verbose_name_plural': 'ტრეილერის დოკუმენტები',
            },
        ),
        migrations.CreateModel(
            name='CarDocuments',
            fields=[
                ('car_doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_doc_number', models.CharField(max_length=22, verbose_name='დოკუემენტის ნომერი')),
                ('car_doc_given', models.DateField(verbose_name='გაცემის თარიღი')),
                ('car_doc_expire', models.DateField(verbose_name='მოქმედების ვადა')),
                ('relevance', models.BooleanField(default=True, verbose_name='აქტუალურობა')),
                ('car_doc_path', models.FileField(upload_to='uploads/car_docs', verbose_name='ფაილი')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardocs.cars', verbose_name='მანქანის ID')),
                ('car_doc_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cardocs.doccategories', verbose_name='კატეგორია')),
            ],
            options={
                'verbose_name_plural': 'მანქანის დოკუმენტები',
            },
        ),
    ]
