# Generated by Django 4.1.1 on 2023-05-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardocs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='car_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/car_photo', verbose_name='ფაილი'),
        ),
    ]
