# Generated by Django 4.1.1 on 2023-08-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardocs', '0003_trailers_trailer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardocuments',
            name='car_doc_number',
            field=models.CharField(max_length=22, verbose_name='დოკუმენტის ნომერი'),
        ),
    ]
