# Generated by Django 4.1.1 on 2023-05-22 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverDocCategories',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=45, verbose_name='კატეგორია')),
            ],
            options={
                'verbose_name_plural': 'მძღოლის საბუთების ნომერი',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('dr_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_name', models.CharField(max_length=15, verbose_name='სახელი')),
                ('dr_surname', models.CharField(max_length=25, verbose_name='გვარი')),
                ('dr_email', models.EmailField(blank=True, max_length=60, null=True, verbose_name='ელ-ფოსტა')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='დაბადების თარიღი')),
                ('dr_personal', models.CharField(max_length=11, null=True, verbose_name='პირადი ნომერი')),
            ],
            options={
                'verbose_name_plural': 'მძღოლები',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_number', models.CharField(default='', max_length=12, verbose_name='დოკუმენტის ნომერი')),
                ('doc_given', models.DateField(verbose_name='გაცემის თარიღი')),
                ('doc_expire', models.DateField(verbose_name='Expire date')),
                ('relevance', models.BooleanField(default=True, verbose_name='აქტუალურობა')),
                ('doc_path', models.FileField(upload_to='uploads/docs', verbose_name='ფაილი')),
                ('doc_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='driverdocs.driverdoccategories', verbose_name='დოკუმენტის კატეგორია')),
                ('dr_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='driverdocs.drivers', verbose_name='მძღოლი')),
            ],
            options={
                'verbose_name_plural': 'მძღოლის საბუთები',
                'managed': True,
            },
        ),
    ]
