# Generated by Django 4.1.1 on 2023-05-23 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driverdocs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverdoccategories',
            options={'managed': True, 'verbose_name_plural': 'მძღოლის საბუთების კატეგორიები'},
        ),
    ]
