# Generated by Django 4.1.1 on 2023-05-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverdocs', '0002_alter_driverdoccategories_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='dr_p_n',
            field=models.CharField(max_length=11, null=True, verbose_name='პირადი ნომერი'),
        ),
    ]
