# Generated by Django 4.1.1 on 2023-05-27 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driverdocs', '0003_drivers_dr_p_n'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivers',
            name='dr_p_n',
        ),
    ]
