# Generated by Django 4.1.1 on 2023-05-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverdocs', '0004_remove_drivers_dr_p_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='dr_phone',
            field=models.CharField(max_length=12, null=True, verbose_name='ტელეფონი'),
        ),
    ]
